version: '2'
services:
  wifi-connect:
    build: ./wifi-connect
    network_mode: "host"
    privileged: true
    labels:
      io.resin.features.dbus: '1'
  web-app:
    build: ./web-app
    depends_on:
      - wifi-connect
    expose:
      - "80"
